GEM_VERSION = $(shell cat ../BBQ_VERSION)
GEM_NAME    = bbq-rails
REQUIRE     = $(GEM_NAME)

include ../support/make/install.mk
include ../support/make/test.mk
include ../support/make/gem.mk
include ../support/make/help.mk
